image: docker:stable
options:
  docker: true
pipelines:
  default:
    - step:
        script:
          - set -eu
          - apk add --no-cache py-pip bash
          - pip install --no-cache-dir docker-compose
          - docker-compose -v
          - scripts/run_tests.sh