apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "contract-manager.fullname" . }}
  labels:
    {{- include "contract-manager.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "contract-manager.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "contract-manager.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "contract-manager.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: TABLE_NAME
              value: {{.Values.env.TABLE_NAME}}
            - name: AWS_ENDPOINT
              value: {{.Values.env.AWS_ENDPOINT}}
            - name: AWS_REGION
              value: {{.Values.env.AWS_REGION}}
            - name: AWS_ACCESS_KEY_ID
              value: {{.Values.env.AWS_ACCESS_KEY_ID}}
            - name: AWS_SECRET_ACCESS_KEY
              value: {{.Values.env.AWS_SECRET_ACCESS_KEY}}
            - name: SSL_ENABLED
              value: {{.Values.env.SSL_ENABLED}}
            - name: PORT
              value: "{{.Values.service.port}}"
          ports:
            - name: grpc
              containerPort: {{.Values.service.port}}
              protocol: TCP
          livenessProbe:
            exec:
              command:
                - /bin/grpc_health_probe
                - -addr=:{{.Values.service.port}}
          readinessProbe:
            exec:
              command:
                - /bin/grpc_health_probe
                - -addr=:{{.Values.service.port}}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
