// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package listener

import (
	"contract-service/storage"
	"github.com/aws/aws-sdk-go/aws"
)

// Injectors from wire.go:

func InitializeListenerService(cfg *aws.Config, bucket string) (EventHandlerService, error) {
	s3, err := storage.NewS3(cfg, bucket)
	if err != nil {
		return nil, err
	}
	eventHandlerService := NewEventHandlerService(s3)
	return eventHandlerService, nil
}
