version: 2.1

jobs:
  test:
    docker:
      - image: cimg/go:1.19

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Run Tests
          command: ./scripts/run_tests.sh


workflows:
  build_and_test:
    jobs:
      - test