// Code generated by MockGen. DO NOT EDIT.
// Source: ./storage/interfaces.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	storage "contract-service/storage"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockTransactionRepository is a mock of TransactionRepository interface.
type MockTransactionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionRepositoryMockRecorder
}

// MockTransactionRepositoryMockRecorder is the mock recorder for MockTransactionRepository.
type MockTransactionRepositoryMockRecorder struct {
	mock *MockTransactionRepository
}

// NewMockTransactionRepository creates a new mock instance.
func NewMockTransactionRepository(ctrl *gomock.Controller) *MockTransactionRepository {
	mock := &MockTransactionRepository{ctrl: ctrl}
	mock.recorder = &MockTransactionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionRepository) EXPECT() *MockTransactionRepositoryMockRecorder {
	return m.recorder
}

// CompleteTransaction mocks base method.
func (m *MockTransactionRepository) CompleteTransaction(ctx context.Context, address, hash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteTransaction", ctx, address, hash)
	ret0, _ := ret[0].(error)
	return ret0
}

// CompleteTransaction indicates an expected call of CompleteTransaction.
func (mr *MockTransactionRepositoryMockRecorder) CompleteTransaction(ctx, address, hash interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteTransaction", reflect.TypeOf((*MockTransactionRepository)(nil).CompleteTransaction), ctx, address, hash)
}

// DeleteTransaction mocks base method.
func (m *MockTransactionRepository) DeleteTransaction(ctx context.Context, address, hash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTransaction", ctx, address, hash)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTransaction indicates an expected call of DeleteTransaction.
func (mr *MockTransactionRepositoryMockRecorder) DeleteTransaction(ctx, address, hash interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTransaction", reflect.TypeOf((*MockTransactionRepository)(nil).DeleteTransaction), ctx, address, hash)
}

// GetAllTransactions mocks base method.
func (m *MockTransactionRepository) GetAllTransactions(ctx context.Context, address string) ([]*storage.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllTransactions", ctx, address)
	ret0, _ := ret[0].([]*storage.Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllTransactions indicates an expected call of GetAllTransactions.
func (mr *MockTransactionRepositoryMockRecorder) GetAllTransactions(ctx, address interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllTransactions", reflect.TypeOf((*MockTransactionRepository)(nil).GetAllTransactions), ctx, address)
}

// GetTransactions mocks base method.
func (m *MockTransactionRepository) GetTransactions(ctx context.Context, address string) ([]*storage.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransactions", ctx, address)
	ret0, _ := ret[0].([]*storage.Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransactions indicates an expected call of GetTransactions.
func (mr *MockTransactionRepositoryMockRecorder) GetTransactions(ctx, address interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransactions", reflect.TypeOf((*MockTransactionRepository)(nil).GetTransactions), ctx, address)
}

// StoreTransaction mocks base method.
func (m *MockTransactionRepository) StoreTransaction(ctx context.Context, token storage.Token) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreTransaction", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreTransaction indicates an expected call of StoreTransaction.
func (mr *MockTransactionRepositoryMockRecorder) StoreTransaction(ctx, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreTransaction", reflect.TypeOf((*MockTransactionRepository)(nil).StoreTransaction), ctx, token)
}

// MockPrivateKeyRepository is a mock of PrivateKeyRepository interface.
type MockPrivateKeyRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPrivateKeyRepositoryMockRecorder
}

// MockPrivateKeyRepositoryMockRecorder is the mock recorder for MockPrivateKeyRepository.
type MockPrivateKeyRepositoryMockRecorder struct {
	mock *MockPrivateKeyRepository
}

// NewMockPrivateKeyRepository creates a new mock instance.
func NewMockPrivateKeyRepository(ctrl *gomock.Controller) *MockPrivateKeyRepository {
	mock := &MockPrivateKeyRepository{ctrl: ctrl}
	mock.recorder = &MockPrivateKeyRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPrivateKeyRepository) EXPECT() *MockPrivateKeyRepositoryMockRecorder {
	return m.recorder
}

// DeletePrivateKey mocks base method.
func (m *MockPrivateKeyRepository) DeletePrivateKey(ctx context.Context, contractAddress string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePrivateKey", ctx, contractAddress)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePrivateKey indicates an expected call of DeletePrivateKey.
func (mr *MockPrivateKeyRepositoryMockRecorder) DeletePrivateKey(ctx, contractAddress interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePrivateKey", reflect.TypeOf((*MockPrivateKeyRepository)(nil).DeletePrivateKey), ctx, contractAddress)
}

// GetPrivateKey mocks base method.
func (m *MockPrivateKeyRepository) GetPrivateKey(ctx context.Context, contractAddress string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPrivateKey", ctx, contractAddress)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPrivateKey indicates an expected call of GetPrivateKey.
func (mr *MockPrivateKeyRepositoryMockRecorder) GetPrivateKey(ctx, contractAddress interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPrivateKey", reflect.TypeOf((*MockPrivateKeyRepository)(nil).GetPrivateKey), ctx, contractAddress)
}

// UpsertPrivateKey mocks base method.
func (m *MockPrivateKeyRepository) UpsertPrivateKey(ctx context.Context, contractAddress, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertPrivateKey", ctx, contractAddress, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertPrivateKey indicates an expected call of UpsertPrivateKey.
func (mr *MockPrivateKeyRepositoryMockRecorder) UpsertPrivateKey(ctx, contractAddress, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertPrivateKey", reflect.TypeOf((*MockPrivateKeyRepository)(nil).UpsertPrivateKey), ctx, contractAddress, key)
}

// MockContractRepository is a mock of ContractRepository interface.
type MockContractRepository struct {
	ctrl     *gomock.Controller
	recorder *MockContractRepositoryMockRecorder
}

// MockContractRepositoryMockRecorder is the mock recorder for MockContractRepository.
type MockContractRepositoryMockRecorder struct {
	mock *MockContractRepository
}

// NewMockContractRepository creates a new mock instance.
func NewMockContractRepository(ctrl *gomock.Controller) *MockContractRepository {
	mock := &MockContractRepository{ctrl: ctrl}
	mock.recorder = &MockContractRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContractRepository) EXPECT() *MockContractRepositoryMockRecorder {
	return m.recorder
}

// DeleteContract mocks base method.
func (m *MockContractRepository) DeleteContract(ctx context.Context, contractAddress, owner string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteContract", ctx, contractAddress, owner)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteContract indicates an expected call of DeleteContract.
func (mr *MockContractRepositoryMockRecorder) DeleteContract(ctx, contractAddress, owner interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteContract", reflect.TypeOf((*MockContractRepository)(nil).DeleteContract), ctx, contractAddress, owner)
}

// GetContract mocks base method.
func (m *MockContractRepository) GetContract(ctx context.Context, contractAddress string) (*storage.Contract, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContract", ctx, contractAddress)
	ret0, _ := ret[0].(*storage.Contract)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContract indicates an expected call of GetContract.
func (mr *MockContractRepositoryMockRecorder) GetContract(ctx, contractAddress interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContract", reflect.TypeOf((*MockContractRepository)(nil).GetContract), ctx, contractAddress)
}

// GetContractsByOwner mocks base method.
func (m *MockContractRepository) GetContractsByOwner(ctx context.Context, owner string) ([]*storage.Contract, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContractsByOwner", ctx, owner)
	ret0, _ := ret[0].([]*storage.Contract)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContractsByOwner indicates an expected call of GetContractsByOwner.
func (mr *MockContractRepositoryMockRecorder) GetContractsByOwner(ctx, owner interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContractsByOwner", reflect.TypeOf((*MockContractRepository)(nil).GetContractsByOwner), ctx, owner)
}

// UpsertContract mocks base method.
func (m *MockContractRepository) UpsertContract(ctx context.Context, contract *storage.Contract) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertContract", ctx, contract)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertContract indicates an expected call of UpsertContract.
func (mr *MockContractRepositoryMockRecorder) UpsertContract(ctx, contract interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertContract", reflect.TypeOf((*MockContractRepository)(nil).UpsertContract), ctx, contract)
}
