// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TransactionServiceClient is the client API for TransactionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TransactionServiceClient interface {
	GetContract(ctx context.Context, in *Address, opts ...grpc.CallOption) (*Contract, error)
	ConstructTransaction(ctx context.Context, in *TransactionRequest, opts ...grpc.CallOption) (*Transaction, error)
	GetTransactions(ctx context.Context, in *Address, opts ...grpc.CallOption) (*Transactions, error)
	CompleteTransaction(ctx context.Context, in *CompleteTransactionRequest, opts ...grpc.CallOption) (*Empty, error)
}

type transactionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTransactionServiceClient(cc grpc.ClientConnInterface) TransactionServiceClient {
	return &transactionServiceClient{cc}
}

func (c *transactionServiceClient) GetContract(ctx context.Context, in *Address, opts ...grpc.CallOption) (*Contract, error) {
	out := new(Contract)
	err := c.cc.Invoke(ctx, "/TransactionService/GetContract", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) ConstructTransaction(ctx context.Context, in *TransactionRequest, opts ...grpc.CallOption) (*Transaction, error) {
	out := new(Transaction)
	err := c.cc.Invoke(ctx, "/TransactionService/ConstructTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) GetTransactions(ctx context.Context, in *Address, opts ...grpc.CallOption) (*Transactions, error) {
	out := new(Transactions)
	err := c.cc.Invoke(ctx, "/TransactionService/GetTransactions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) CompleteTransaction(ctx context.Context, in *CompleteTransactionRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/TransactionService/CompleteTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TransactionServiceServer is the server API for TransactionService service.
// All implementations must embed UnimplementedTransactionServiceServer
// for forward compatibility
type TransactionServiceServer interface {
	GetContract(context.Context, *Address) (*Contract, error)
	ConstructTransaction(context.Context, *TransactionRequest) (*Transaction, error)
	GetTransactions(context.Context, *Address) (*Transactions, error)
	CompleteTransaction(context.Context, *CompleteTransactionRequest) (*Empty, error)
	mustEmbedUnimplementedTransactionServiceServer()
}

// UnimplementedTransactionServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTransactionServiceServer struct {
}

func (UnimplementedTransactionServiceServer) GetContract(context.Context, *Address) (*Contract, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetContract not implemented")
}
func (UnimplementedTransactionServiceServer) ConstructTransaction(context.Context, *TransactionRequest) (*Transaction, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConstructTransaction not implemented")
}
func (UnimplementedTransactionServiceServer) GetTransactions(context.Context, *Address) (*Transactions, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTransactions not implemented")
}
func (UnimplementedTransactionServiceServer) CompleteTransaction(context.Context, *CompleteTransactionRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompleteTransaction not implemented")
}
func (UnimplementedTransactionServiceServer) mustEmbedUnimplementedTransactionServiceServer() {}

// UnsafeTransactionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TransactionServiceServer will
// result in compilation errors.
type UnsafeTransactionServiceServer interface {
	mustEmbedUnimplementedTransactionServiceServer()
}

func RegisterTransactionServiceServer(s grpc.ServiceRegistrar, srv TransactionServiceServer) {
	s.RegisterService(&TransactionService_ServiceDesc, srv)
}

func _TransactionService_GetContract_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Address)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).GetContract(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/TransactionService/GetContract",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).GetContract(ctx, req.(*Address))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_ConstructTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).ConstructTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/TransactionService/ConstructTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).ConstructTransaction(ctx, req.(*TransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_GetTransactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Address)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).GetTransactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/TransactionService/GetTransactions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).GetTransactions(ctx, req.(*Address))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_CompleteTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).CompleteTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/TransactionService/CompleteTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).CompleteTransaction(ctx, req.(*CompleteTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TransactionService_ServiceDesc is the grpc.ServiceDesc for TransactionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TransactionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "TransactionService",
	HandlerType: (*TransactionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetContract",
			Handler:    _TransactionService_GetContract_Handler,
		},
		{
			MethodName: "ConstructTransaction",
			Handler:    _TransactionService_ConstructTransaction_Handler,
		},
		{
			MethodName: "GetTransactions",
			Handler:    _TransactionService_GetTransactions_Handler,
		},
		{
			MethodName: "CompleteTransaction",
			Handler:    _TransactionService_CompleteTransaction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/contractManagement.proto",
}

// ContractManagementClient is the client API for ContractManagement service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ContractManagementClient interface {
	Get(ctx context.Context, in *Address, opts ...grpc.CallOption) (*Contract, error)
	Store(ctx context.Context, in *Contract, opts ...grpc.CallOption) (*Empty, error)
	Delete(ctx context.Context, in *AddressOwner, opts ...grpc.CallOption) (*Empty, error)
	List(ctx context.Context, in *Owner, opts ...grpc.CallOption) (*Contracts, error)
}

type contractManagementClient struct {
	cc grpc.ClientConnInterface
}

func NewContractManagementClient(cc grpc.ClientConnInterface) ContractManagementClient {
	return &contractManagementClient{cc}
}

func (c *contractManagementClient) Get(ctx context.Context, in *Address, opts ...grpc.CallOption) (*Contract, error) {
	out := new(Contract)
	err := c.cc.Invoke(ctx, "/ContractManagement/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contractManagementClient) Store(ctx context.Context, in *Contract, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/ContractManagement/Store", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contractManagementClient) Delete(ctx context.Context, in *AddressOwner, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/ContractManagement/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contractManagementClient) List(ctx context.Context, in *Owner, opts ...grpc.CallOption) (*Contracts, error) {
	out := new(Contracts)
	err := c.cc.Invoke(ctx, "/ContractManagement/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContractManagementServer is the server API for ContractManagement service.
// All implementations must embed UnimplementedContractManagementServer
// for forward compatibility
type ContractManagementServer interface {
	Get(context.Context, *Address) (*Contract, error)
	Store(context.Context, *Contract) (*Empty, error)
	Delete(context.Context, *AddressOwner) (*Empty, error)
	List(context.Context, *Owner) (*Contracts, error)
	mustEmbedUnimplementedContractManagementServer()
}

// UnimplementedContractManagementServer must be embedded to have forward compatible implementations.
type UnimplementedContractManagementServer struct {
}

func (UnimplementedContractManagementServer) Get(context.Context, *Address) (*Contract, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedContractManagementServer) Store(context.Context, *Contract) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Store not implemented")
}
func (UnimplementedContractManagementServer) Delete(context.Context, *AddressOwner) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedContractManagementServer) List(context.Context, *Owner) (*Contracts, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedContractManagementServer) mustEmbedUnimplementedContractManagementServer() {}

// UnsafeContractManagementServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ContractManagementServer will
// result in compilation errors.
type UnsafeContractManagementServer interface {
	mustEmbedUnimplementedContractManagementServer()
}

func RegisterContractManagementServer(s grpc.ServiceRegistrar, srv ContractManagementServer) {
	s.RegisterService(&ContractManagement_ServiceDesc, srv)
}

func _ContractManagement_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Address)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContractManagementServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ContractManagement/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContractManagementServer).Get(ctx, req.(*Address))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContractManagement_Store_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Contract)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContractManagementServer).Store(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ContractManagement/Store",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContractManagementServer).Store(ctx, req.(*Contract))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContractManagement_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddressOwner)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContractManagementServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ContractManagement/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContractManagementServer).Delete(ctx, req.(*AddressOwner))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContractManagement_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Owner)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContractManagementServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ContractManagement/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContractManagementServer).List(ctx, req.(*Owner))
	}
	return interceptor(ctx, in, info, handler)
}

// ContractManagement_ServiceDesc is the grpc.ServiceDesc for ContractManagement service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ContractManagement_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ContractManagement",
	HandlerType: (*ContractManagementServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _ContractManagement_Get_Handler,
		},
		{
			MethodName: "Store",
			Handler:    _ContractManagement_Store_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _ContractManagement_Delete_Handler,
		},
		{
			MethodName: "List",
			Handler:    _ContractManagement_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/contractManagement.proto",
}
