# Default values for dynamodb.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: amazon/dynamodb-local
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

service:
  type: NodePort
  port: 8000


TableBootstrap:
  Image:
    Repository: amazon/aws-cli
    Tag: latest
    PullPolicy: IfNotPresent