// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package signing

import (
	"contract-service/storage"
	"github.com/aws/aws-sdk-go/aws"
	"google.golang.org/grpc"
)

// Injectors from wire.go:

func InitializeSigningServer(host int, opts []grpc.ServerOption, tableName string, cfg ...*aws.Config) (*SignerRPCService, error) {
	signingService := NewSigningService()
	privateKeyRepository, err := storage.NewPrivateKeyRepository(tableName, cfg...)
	if err != nil {
		return nil, err
	}
	signerRPCService, err := NewSignerServer(host, opts, signingService, privateKeyRepository)
	if err != nil {
		return nil, err
	}
	return signerRPCService, nil
}
